#!/data/data/com.termux/files/usr/bin/bash

#export PATH=/data/data/jackpal.androidterm/bin/:$PATH

month=`date | busybox awk '{print $2}'`;
echo "Current Month: $month"

day=`date | busybox awk '{print $3}'`;
echo "Current Day: $day"

time=`date | busybox grep -o "[0-9]*:[0-9]*:[0-9]*" | busybox sed -e 's/://g'`;
echo "Current Time: $time"

